import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import ts from 'typescript';
async function load(name){const s=await readFile(new URL('../src/'+name+'.ts',import.meta.url),'utf8');return import('data:text/javascript;base64,'+Buffer.from(ts.transpileModule(s,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText).toString('base64'));}
const p=await load('presentation'),d=await load('display');
test('selected service failure rises but hidden service does not control red border',()=>{assert.equal(p.overviewPriority({services:[{pinned:true,state:'app_fail'}]},true),2);assert.equal(p.overviewPriority({has_problem:true,unselected_service_problems:4,services:[]},true),0);assert.equal(p.overviewPriority({services:[{pinned:false,state:'app_fail'}]},true),0);});
test('metric breach, stale contact, and paused checks have distinct priority',()=>{assert.equal(p.overviewPriority({breaches:[{metric:'cpu'}]},true),2);assert.equal(p.overviewPriority({breaches:[{metric:'cpu'}]},false),0);assert.equal(p.overviewPriority({state:'unreachable'},false),1);assert.equal(p.overviewPriority({services:[{state:'paused'}]},true),0);});
test('priority order is stable and does not mutate incoming snapshots',()=>{const rows=[{id:'a',name:'A'},{id:'z',name:'Z',breaches:[{metric:'disk'}]},{id:'b',name:'B'}];assert.deepEqual(p.orderOverview(rows,()=>true).map(v=>v.id),['z','a','b']);assert.equal(rows[0].id,'a');});
test('TV default is approximately 30 percent smaller and selection is bounded',()=>{assert.equal(d.tvDensity(null),'10');assert.ok(10/14>=.7&&10/14<.73);assert.equal(d.tvDensity('14'),'14');assert.equal(d.tvDensity('1'),'10');assert.ok(d.boardCapacity(540,110,60)>=6);});
test('console never persists authentication or auto reconnects',async()=>{const s=await readFile(new URL('../src/pages/Console.vue',import.meta.url),'utf8');assert.ok(!s.includes('localStorage'));assert.ok(!s.includes('sessionStorage'));assert.ok(s.includes('credentialsClear()'));assert.ok(s.includes('onBeforeRouteUpdate'));assert.ok(s.includes('registerOscHandler(52'));assert.ok(s.includes("url.protocol='wss:'"));});
test('service rename uses an independent operation with previous name',async()=>{const s=await readFile(new URL('../src/components/ServiceNameEditor.vue',import.meta.url),'utf8');assert.ok(s.includes("'service.rename'"));assert.ok(s.includes('expected_name'));assert.ok(!s.includes('check.apply'));});
