import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import ts from 'typescript';
async function load(name){const text=await readFile(new URL('../src/'+name+'.ts',import.meta.url),'utf8');return import('data:text/javascript;base64,'+Buffer.from(ts.transpileModule(text,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText).toString('base64'));}
const display=await load('display'), selection=await load('serviceSelection');
test('TV and compact mode are explicit, unknown values cannot inject CSS',()=>{for(const s of ['x',';color:red',null,undefined])assert.equal(display.displayMode(s),'auto');assert.equal(display.displayMode('tv'),'tv');assert.equal(display.displayMode('compact'),'compact');});
test('TV density is bounded to tested values',()=>{assert.equal(display.tvDensity('12'),'12');assert.equal(display.tvDensity(10),'10');for(const x of ['1','300',NaN])assert.equal(display.tvDensity(x),'10');});
test('960x540 CSS screen fits several TV rows without zoom',()=>{assert.ok(display.boardCapacity(540,130,86)>=4);assert.ok(display.boardCapacity(1080,150,86)>=10);});
test('TV capacity handles unavailable sizes and always permits navigation',()=>{assert.equal(display.boardCapacity(0,50,86),1);assert.equal(display.boardCapacity(Infinity,50,86),1);assert.equal(display.boardCapacity(1080,50,0),1);});
test('page slice handles data shrink and empty fleet',()=>{assert.deepEqual(display.pageSlice([],8,3),{rows:[],page:0,pages:1});assert.deepEqual(display.pageSlice([1,2,3,4,5],9,2),{rows:[5],page:2,pages:3});});
test('paging does not change machine order or source',()=>{const a=[4,3,2,1];assert.deepEqual(display.pageSlice(a,1,2).rows,[2,1]);assert.deepEqual(a,[4,3,2,1]);});
test('service ages without network events and respects slow intervals',()=>{const now=Date.now();const s={fresh:true,observation:{observed_at:new Date(now-21000).toISOString(),interval_seconds:5}};assert.equal(display.serviceFresh(s,now),false);s.observation.interval_seconds=30;assert.equal(display.serviceFresh(s,now),true);});
test('paused/future/missing service data cannot be freshly green',()=>{assert.equal(display.serviceFresh({fresh:false}),false);assert.equal(display.serviceFresh({fresh:true}),false);assert.equal(display.serviceFresh({fresh:true,observation:{observed_at:new Date(Date.now()+60000).toISOString()}}),false);});
test('disable monitoring preserves custom body, secrets, interval and ignored status',()=>{const original={id:'c',service_id:'s',method:'POST',body:'{"query":"health"}',body_secret_id:'secret',interval_seconds:30,ignored:true};const off=selection.monitoringCheck(original,false);assert.equal(off.paused,true);assert.equal(off.ignored,true);assert.equal(off.body,original.body);assert.equal(off.body_secret_id,'secret');assert.equal(off.interval_seconds,30);assert.equal(original.paused,undefined);});
test('enable is explicit and missing definitions cannot fake success',()=>{assert.equal(selection.monitoringCheck({id:'c',service_id:'s',ignored:true},true).ignored,false);assert.throws(()=>selection.monitoringCheck({},true));});
test('monitoring status distinguishes desired/applied/global pause',()=>{assert.equal(selection.monitoringLabel({has_check:true,monitoring_applied:false,monitoring_enabled:false}),'Отключение ожидает агента');assert.equal(selection.monitoringLabel({has_check:true,monitoring_applied:true,monitoring_enabled:true,globally_paused:true}),'Общая пауза машины');});
// Source contract tests complement, never replace, the real browser suite.
test('login uses password manager attributes, bounded remember choice and non-submitting eye',async()=>{const login=await readFile(new URL('../src/pages/Login.vue',import.meta.url),'utf8');const input=await readFile(new URL('../src/components/PasswordInput.vue',import.meta.url),'utf8');assert.ok(login.includes('autocomplete="username"'));assert.ok(login.includes('Запомнить вход на 30 дней'));assert.ok(input.includes('type="button"'));assert.ok(input.includes('current-password'));assert.ok(!login.includes('localStorage'));});
test('monitoring toggle reads the actual DTO and pin remains server-only',async()=>{const toggle=await readFile(new URL('../src/components/ServiceMonitorToggle.vue',import.meta.url),'utf8');const pin=await readFile(new URL('../src/components/ServiceOverviewToggle.vue',import.meta.url),'utf8');assert.ok(toggle.includes('result.desired_config'));assert.ok(!toggle.includes('result.agent.desired_config'));assert.ok(toggle.includes("submitOp('check.apply'"));assert.ok(pin.includes("submitOp('service.pin'"));assert.ok(!pin.includes('check.apply'));});
test('TV CSS does not use transform scaling or disable zoom',async()=>{const css=await readFile(new URL('../src/styles.css',import.meta.url),'utf8');const html=await readFile(new URL('../index.html',import.meta.url),'utf8');assert.ok(css.includes('.tv-machine'));assert.ok(css.includes('.tv-mode .main {max-width:none;}'));assert.ok(!/user-scalable\s*=\s*no/i.test(html));assert.ok(!css.includes('transform: scale'));});

test('explicit TV link cannot override a later saved choice on reload',async()=>{const text=await readFile(new URL('../src/composables/useDisplay.ts',import.meta.url),'utf8');assert.ok(text.includes("url.searchParams.set('display',mode.value)"));assert.ok(text.includes('window.history.replaceState'));});
