import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import ts from 'typescript';
const source=await readFile(new URL('../src/checkDraft.ts',import.meta.url),'utf8');const js=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;const c=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
const form=()=>c.loadCheck({}, {id:'s',url:'http://127.0.0.1:8080',dial_target:'127.0.0.1:8080'});
test('Save and Trial builder retains exact request and schedule',()=>{const f=form();Object.assign(f,{method:'POST',allowPOST:true,path:'/rpc?mode=brief',headers:'{"Content-Type":"application/json"}',body:'{"method":"health"}',interval:30,timeout:10});const d=c.buildCheck(f,'c');assert.equal(d.body,f.body);assert.equal(d.path,f.path);assert.equal(d.interval_seconds,30);assert.equal(d.timeout_seconds,10);assert.equal(d.request_version,1);});
test('POST preset cannot silently grant periodic request consent',()=>{const f=c.applyPreset(form(),'rpc');assert.equal(f.allowPOST,false);assert.throws(()=>c.buildCheck(f,'c'),/Подтвердите/)});
test('Selecting a template resets inherited body expectations and method',()=>{const f=c.applyPreset({...form(),method:'POST',body:'old',bodySecretID:'private',allowPOST:true},'spring');assert.equal(f.method,'GET');assert.equal(f.body,'');assert.equal(f.bodySecretID,'');assert.equal(f.jsonValue,'UP');});
test('Explicit path can be cleared and is not re-inherited invisibly',()=>{const f=c.loadCheck({id:'c',path:'/old?x=1'},{id:'s',url:'http://127.0.0.1'});f.path='';assert.equal(c.buildCheck(f,'unused').path,'');});
test('Intervals, HEAD predicates and simultaneous body sources reject',()=>{for(const edits of [{interval:6},{interval:5,timeout:5},{method:'HEAD',kind:'http_health',expectHealth:true},{method:'POST',allowPOST:true,body:'{}',bodySecretID:'secret'}])assert.throws(()=>c.buildCheck(Object.assign(form(),edits),'c'));});
test('JSON headers must be a bounded string map',()=>{for(const headers of ['[1]','null','{"X-Test":3}','broken'])assert.throws(()=>c.buildCheck({...form(),headers},'c'));});
test('Fresh draft is not a false existing config ID',()=>{assert.equal(c.buildCheck(form(),'stable-check').id,'stable-check')});
test('refused is a transport diagnosis, not bad path or missing auth',()=>{assert.match(c.serviceHint({transport:'refused'}),/до отправки HTTP/);assert.match(c.serviceHint({http_status:401}),/секрет/);assert.match(c.serviceHint({http_status:404}),/маршрут/)});

test('Editing a paused or ignored check and applying a template preserves lifecycle flags',()=>{const f=c.loadCheck({paused:true,ignored:true},{id:'s',url:'http://127.0.0.1'});for(const d of [c.buildCheck(f,'c'),c.buildCheck(c.applyPreset(f,'spring'),'c')]){assert.equal(d.paused,true);assert.equal(d.ignored,true);}});
test('Offline attention_required is not a completed trial and rejection is not success',()=>{assert.equal(c.checkOperationFeedback({action:'check.trial',status:'attention_required',targets:[{status:'waiting_offline'}]}).done,false);const failed=c.checkOperationFeedback({action:'check.trial',targets:[{status:'rejected',message:'unsupported'}]});assert.equal(failed.done,true);assert.match(failed.message,/не подтверждена/);assert.doesNotMatch(failed.message,/запрос завершён/);});
test('Trial completion requires evidence and successful job does not promise healthy service',()=>{assert.match(c.checkOperationFeedback({action:'check.trial',targets:[{status:'succeeded'}]}).message,/отсутствуют/);const f=c.checkOperationFeedback({action:'check.trial',targets:[{status:'succeeded',evidence:{trial:true,app_result:'fail'}}]});assert.equal(f.done,true);assert.match(f.message,/не сохранено/);assert.doesNotMatch(f.message,/сервис здоров/i);});
test('Queued trial flag without vantage is not a completed result',()=>{const queued=c.checkOperationFeedback({action:'check.trial',targets:[{status:'queued',evidence:{trial:true,url:'http://127.0.0.1'}}]});assert.equal(queued.done,false);});
