import {test,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import ts from 'typescript';
async function load(name){const s=await readFile(new URL('../src/'+name+'.ts',import.meta.url),'utf8');return import('data:text/javascript;base64,'+Buffer.from(ts.transpileModule(s,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText).toString('base64'));}
const ops=await load('operations'),api=await load('api');
beforeEach(()=>{globalThis.window=new EventTarget();globalThis.sessionStorage={getItem:()=>null,setItem:()=>{throw Error('must not persist a read notice as an execution request')},removeItem:()=>{}};api.setCsrf('csrf-test');});
const response=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}});
test('read removes notification without changing failed execution',()=>{const op={status:'completed_with_errors',attention_required:true,read:false};assert.equal(ops.requiresAttention(op),true);op.read=true;assert.equal(ops.requiresAttention(op),false);assert.equal(op.status,'completed_with_errors');});
test('mixed running operation still surfaces failed targets',()=>{assert.equal(ops.requiresAttention({status:'running',targets:[{status:'failed'}]}),true);assert.equal(ops.requiresAttention({status:'running',targets:[{status:'succeeded'}]}),false);});
test('explicit server attention overrides fallback and new notice is red',()=>{assert.equal(ops.requiresAttention({status:'completed_with_errors',attention_required:false}),false);assert.equal(ops.requiresAttention({status:'running',attention_required:true,read:false}),true);});
test('read selection captures a version and refuses missing unsafe versions',()=>{const o={operation_id:'a',attention_revision:4};const r=ops.readTarget(o);o.attention_revision=5;assert.deepEqual(r,{operation_id:'a',attention_revision:4});for(const bad of [0,-1,1.5,NaN,undefined,Number.MAX_SAFE_INTEGER+1])assert.throws(()=>ops.readTarget({operation_id:'a',attention_revision:bad}));});
test('operation query safely encodes literal search and cursor',()=>{const u=new URL(ops.operationQuery('errors','read','a&b%_ Ж','abc/='),'https://example.invalid');assert.equal(u.searchParams.get('q'),'a&b%_ Ж');assert.equal(u.searchParams.get('before'),'abc/=');assert.equal(u.searchParams.get('limit'),'50');assert.equal(u.searchParams.get('read'),'read');});
test('read uses CSRF-protected metadata endpoint, not a job or browser pending queue',async()=>{let refresh=0;window.addEventListener('monik:refresh',()=>refresh++);globalThis.fetch=async(path,init)=>{assert.equal(path,'/api/v1/operations/read');assert.equal(init.headers.get('X-CSRF-Token'),'csrf-test');assert.deepEqual(JSON.parse(init.body),{targets:[{operation_id:'a',attention_revision:4}],read:true});return response({saved:true,count:1});};await api.markOperationsRead([{operation_id:'a',attention_revision:4}],true);assert.equal(refresh,1);});
test('lost read response is not retried or claimed successful',async()=>{let calls=0,refresh=0;window.addEventListener('monik:refresh',()=>refresh++);globalThis.fetch=async()=>{calls++;throw Error('lost');};await assert.rejects(api.markOperationsRead([{operation_id:'a',attention_revision:4}],true),e=>e.status===0);assert.equal(calls,1);assert.equal(refresh,0);});
test('new-attention conflict remains actionable',async()=>{globalThis.fetch=async()=>response({error:'attention_conflict',message:'refresh selection'},409);await assert.rejects(api.markOperationsRead([{operation_id:'a',attention_revision:3}],true),e=>e.status===409&&e.error==='attention_conflict');});
test('missing commit acknowledgement is not saved success',async()=>{globalThis.fetch=async()=>response({});await assert.rejects(api.markOperationsRead([{operation_id:'a',attention_revision:1}],false),e=>e.error==='invalid_response');});
test('read failure cannot erase a failed action during request reconciliation',async()=>{globalThis.sessionStorage={getItem:()=>null,setItem:()=>{},removeItem:()=>{}};globalThis.fetch=async()=>response({operation_id:'a',status:'completed_with_errors',read:true,targets:[{message:'failure remains'}]});await assert.rejects(api.submitOp('agent.pin',{agent_id:'a'}),e=>e.error==='operation_attention');});
